-- MySQL Script generated by MySQL Workbench
-- Tue May 17 22:14:09 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema openremotedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema openremotedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `openremotedb` DEFAULT CHARACTER SET utf8 ;
USE `openremotedb` ;

-- -----------------------------------------------------
-- Table `openremotedb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openremotedb`.`account` ;

CREATE TABLE IF NOT EXISTS `openremotedb`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  `passwordHash` VARCHAR(45) NOT NULL,
  `salt` BINARY(32) NOT NULL,
  `cipherKey` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openremotedb`.`inputvalue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openremotedb`.`inputvalue` ;

CREATE TABLE IF NOT EXISTS `openremotedb`.`inputvalue` (
  `number` TINYINT UNSIGNED NOT NULL,
  `timeStamp` TIMESTAMP NOT NULL,
  `id` INT NOT NULL,
  `value` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`number`, `timeStamp`, `id`),
  INDEX `fk_inputvalue_account1_idx` (`id` ASC),
  CONSTRAINT `fk_inputvalue_account1`
    FOREIGN KEY (`id`)
    REFERENCES `openremotedb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openremotedb`.`configuration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openremotedb`.`configuration` ;

CREATE TABLE IF NOT EXISTS `openremotedb`.`configuration` (
  `id` INT NOT NULL,
  `sendInterval` INT UNSIGNED NULL DEFAULT 5000,
  `errorInterval` INT UNSIGNED NULL DEFAULT 4000,
  `errorCount` TINYINT UNSIGNED NULL DEFAULT 6,
  `notifications` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_configuration_account1`
    FOREIGN KEY (`id`)
    REFERENCES `openremotedb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openremotedb`.`channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openremotedb`.`channel` ;

CREATE TABLE IF NOT EXISTS `openremotedb`.`channel` (
  `number` TINYINT UNSIGNED NOT NULL,
  `id` INT NOT NULL,
  `lowTriggerValue` INT UNSIGNED NULL DEFAULT 0,
  `highTriggerValue` INT UNSIGNED NULL DEFAULT 1023,
  `triggerMode` TINYINT UNSIGNED NULL DEFAULT 0,
  `outputMode` TINYINT UNSIGNED NULL DEFAULT 1,
  `unitOffset` DOUBLE NULL DEFAULT 0,
  `unitFactor` DOUBLE NULL DEFAULT 1,
  `unitName` VARCHAR(45) NULL DEFAULT 'Unit',
  `inputLabel` VARCHAR(45) NULL,
  `outputLabel` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`number`, `id`),
  INDEX `fk_channel_account1_idx` (`id` ASC),
  CONSTRAINT `fk_channel_account1`
    FOREIGN KEY (`id`)
    REFERENCES `openremotedb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
